# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "profile"
##
description: Execute functional profiling tools
keywords:
  - microbiome
  - metagenome
  - fastq
  - function
components:
  - humann/humann
  - fmhfunprofiler
  - mifaser
  - rgi/bwt

## TODO nf-core: List all of the channels used as input with a description and their structure
input:
 - reads:
      type: file
      description: |
        The input channel containing paired fastq files
        Structure: [ val(meta), path(fastq) ]
      pattern: "*.{.fastq}*"
 - reads_concat:
      type: file
      description: |
        The input channel containing concatenated fastq pairs as a single fastq
        Structure: [ val(meta), path(fastq) ]
      pattern: "*.{.fastq}*"
 - databases:
      type: file
      description: |
        The input channel containing the database files
        Structure: [ val(meta), path(file) ]
## TODO nf-core: List all of the channels used as output with a descriptions and their structure
output:
  - profiles:
      type: file
      description: |
        Channel containing tabular profiling results
        Structure: [ val(meta), path(paths) ]
      pattern: "*.bam"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
  - mqc:
      type: file
      description: |
        File containing MultiQC files
        Structure: [ path(file) ]
      pattern: "*"
authors:
  - "@nickp60"
maintainers:
  - "@nickp60"
